### ISSUE TITLE
Feat: 그룹 게시판 UI 구현

### ISSUE THREAD

**Issue by angryeon7** [Wake-up-together-TogetUp/Togetup-iOS-Refatoring#13]
## Issue

* 그룹 게시판 UI 구현
## To-do

- [x] 게시판 달력 구현
- [x] 미션 사진 게시판
- [x] 테마 이미지 로고
