### ISSUE TITLE
Feat: 캘린더 네트워크 연결 작업

### ISSUE THREAD

**Issue by angryeon7** [Wake-up-together-TogetUp/Togetup-iOS-Refatoring#17]
## Issue

* 그룹 캘린더 API 연결
## To-do

- [x] 그룹 생성 뷰 연결
- [x] 그룹 ListVIew 연결
- [x] 그룹 데이터 불러오기
- [x] 캘린더 데이터 관리
