### ISSUE TITLE
Feat: 아바타 탭 UI & UX 구현 및 네트워킹

### ISSUE THREAD

**Issue by yaewonLee** [Wake-up-together-TogetUp/Togetup-iOS-Refatoring#3]
## Issue

* 아바타 변경 컬렉션뷰 UI&UX 및 네트워킹
## To-do

- [x] 로그인후 아바타 상태 저장
- [x] 캐릭터 상태에 따른 cell 상태 반영
- [x] 아바타 상태 변경 시 서버에 전송
