### ISSUE TITLE
Feat: 그룹탭 메인 UI & UX 구현

### ISSUE THREAD

**Issue by angryeon7** [Wake-up-together-TogetUp/Togetup-iOS-Refatoring#4]
## Issue

그룹만들기 로직 시작화면 구현 및 네트워킹

## To-do

- [x] 메인 홈 UIUX 구현
- [x] 개설 페이지 UIUX 구현
- [x] 알림설정 페이지 구현
