### ISSUE TITLE
Refactor: Setting 탭 클린 아키텍쳐 도입

### ISSUE THREAD

**Issue by yaewonLee** [Wake-up-together-TogetUp/Togetup-iOS-Refatoring#56]
## Issue

* Setting 탭 클린 아키텍쳐 도입
## To-do

- [x] 반복 코드 개선
- [ ] input output 도입
- [x] 코드 구조 리팩토링
