### ISSUE TITLE
Feat: 출시에 필요한 기타 기능들 구현

### ISSUE THREAD

**Issue by yaewonLee** [Wake-up-together-TogetUp/Togetup-iOS-Refatoring#9]
## Issue

* 출시 전에 필요한 나머지 기능들 구현

## To-do

-  [x]  아바타 수정된 api 반영
- [x]  브리핑 보드 데이터 있는데도 없다는 문구 나오는 문제 수정
- [x]  강제 업데이트 알럿 추가 및 api 반영
- [x]  개인정보 이용약관 웹뷰
- [x]  se3 UI 기기 대응(온보딩, 알람목록)
